version: '3.8'

services:
  word-excel-replace:
    build: .
    ports:
      - "8501:8501"
    restart: no
    environment:
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
    volumes:
      #- ./data:/app/data  # 可选：数据持久化